server:
  port: 8888


spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8




family:
  familyName: "happy family"
  father:
    name: zimug
    age: ${random.int(20,30)}
  mother:
    alias:
      - lovely
      - ailice
  child:
    name: ${family.father.name:zimug2}
    age: 5
    friends:
      - hobby: football
        sex: male
      - hobby: basketball
        sex: female