server:
  port: 8887

spring:
  datasource:
    url: jdbc:mysql://119.45.56.227:3306/testdb?useUnicodetrue&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      test-on-borrow: true
      test-while-idle: true

mybatis:
  mapper-locations: classpath*:generator/**/*.xml
  type-aliases-package: com.xschen.boot.launch.generator.model
  configuration:
    map-underscore-to-camel-case: true

  logging:
    level:
      com.xschen.boot.launch: debug